# Generated by Django 4.1.5 on 2023-03-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("total_order_amount", models.IntegerField()),
                (
                    "purchase_order_status",
                    models.CharField(
                        choices=[
                            (0, "pending"),
                            (1, "hold"),
                            (2, "shipped"),
                            (3, "cancelled"),
                        ],
                        max_length=1200,
                    ),
                ),
                ("shipped_date", models.DateTimeField(blank=True, null=True)),
                ("purchase_date", models.DateTimeField(blank=True, null=True)),
                ("cancelDate", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_user_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "d_order",
            },
        ),
        migrations.CreateModel(
            name="OrderList",
            fields=[
                (
                    "order_list_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("total_price", models.DecimalField(decimal_places=8, max_digits=32)),
                ("total_number", models.IntegerField()),
            ],
            options={"verbose_name": "order list", "db_table": "d_order_list",},
        ),
        migrations.CreateModel(
            name="ReviewAndRating",
            fields=[
                ("review_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "customer_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ],
                        null=True,
                    ),
                ),
                ("review", models.TextField(blank=True, null=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "shopping_cart_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("count_number", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="goods.product",
                    ),
                ),
            ],
            options={"verbose_name": "shopping cart", "db_table": "d_shoppingcart",},
        ),
    ]
